import mongoose from 'mongoose';

const ambulanceSchema = new mongoose.Schema(
  {
    vehicleNumber: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    driver: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      unique: true, // A driver is assigned to at most one ambulance
    },
    driverContact: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      required: true,
      enum: ['available', 'assigned', 'busy'],
      default: 'available',
    },
    currentLatitude: {
      type: Number,
      required: true,
      default: 19.0760,
    },
    currentLongitude: {
      type: Number,
      required: true,
      default: 72.8777,
    },
    // 6-digit Indian PIN code — informational/display only. The actual
    // "nearby" search uses the geospatial `location` field below, NOT
    // this field. See backend/utils/geoSearch.js.
    pincode: {
      type: String,
      trim: true,
      default: '',
      validate: {
        validator: (v) => v === '' || /^[1-9][0-9]{5}$/.test(v),
        message: 'Pincode must be a valid 6-digit Indian PIN code.',
      },
      index: true,
    },
    // GeoJSON point, kept in sync with currentLatitude/currentLongitude via
    // the pre-save hook below. Required for MongoDB's $near geospatial
    // queries. Coordinate order is [lng, lat] per the GeoJSON spec.
    location: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
      },
      coordinates: {
        type: [Number],
        default: [72.8777, 19.0760],
      },
    },
    hospitalAssigned: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Hospital',
      required: true,
    },
    availability: {
      type: Boolean,
      default: true,
    },
    // True for ambulances auto-created by the nearby-facility provisioner
    // (see backend/utils/autoProvision.js) so a search from any location
    // always has realistic nearby results, not just around the seed data.
    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

ambulanceSchema.index({ location: '2dsphere' });

// Keeps the GeoJSON `location` field in sync whenever the ambulance's
// current position changes, so existing code reading/writing
// currentLatitude/currentLongitude keeps working unmodified, while $near
// geospatial queries also work.
ambulanceSchema.pre('save', function syncLocation(next) {
  if (this.isModified('currentLatitude') || this.isModified('currentLongitude') || this.isNew) {
    this.location = { type: 'Point', coordinates: [this.currentLongitude, this.currentLatitude] };
  }
  next();
});

const Ambulance = mongoose.model('Ambulance', ambulanceSchema);
export default Ambulance;
