import mongoose from 'mongoose';

const hospitalSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      unique: true,
    },
    name: {
      type: String,
      required: true,
      trim: true,
    },
    address: {
      type: String,
      required: true,
    },
    contact: {
      type: String,
      required: true,
    },
    emergencyContact: {
      type: String,
      required: true,
    },
    totalBeds: {
      type: Number,
      required: true,
      default: 0,
    },
    availableBeds: {
      type: Number,
      required: true,
      default: 0,
    },
    icuBedsTotal: {
      type: Number,
      required: true,
      default: 0,
    },
    icuBedsAvailable: {
      type: Number,
      required: true,
      default: 0,
    },
    oxygenBedsTotal: {
      type: Number,
      required: true,
      default: 0,
    },
    oxygenBedsAvailable: {
      type: Number,
      required: true,
      default: 0,
    },
    // Dedicated emergency-bay capacity, distinct from general ward beds,
    // used specifically when ambulance staff are choosing a hospital for
    // an active accident/trauma case.
    emergencyBedsTotal: {
      type: Number,
      required: true,
      default: 0,
    },
    emergencyBedsAvailable: {
      type: Number,
      required: true,
      default: 0,
    },
    hasTraumaCenter: {
      type: Boolean,
      default: false,
    },
    doctorsAvailable: {
      type: Number,
      required: true,
      default: 0,
    },
    rating: {
      type: Number,
      required: true,
      default: 5.0,
      min: 1.0,
      max: 5.0,
    },
    images: {
      type: [String],
      default: [],
    },
    latitude: {
      type: Number,
      required: true,
      default: 19.0760, // Default to Mumbai
    },
    longitude: {
      type: Number,
      required: true,
      default: 72.8777,
    },
    // 6-digit Indian PIN code for the hospital's physical location.
    // Informational/display field — the actual "nearby" search uses the
    // geospatial `location` field below, NOT this field, because most
    // pincodes only have 1-2 hospitals and exact-match would return empty
    // results constantly. See backend/utils/geoSearch.js.
    pincode: {
      type: String,
      trim: true,
      default: '',
      validate: {
        validator: (v) => v === '' || /^[1-9][0-9]{5}$/.test(v),
        message: 'Pincode must be a valid 6-digit Indian PIN code.',
      },
      index: true,
    },
    // GeoJSON point, kept in sync with latitude/longitude via the pre-save
    // hook below. Required for MongoDB's $near geospatial queries (needs a
    // 2dsphere index, which only works on GeoJSON — plain lat/lng number
    // fields can't be indexed this way). Coordinate order is [lng, lat],
    // per the GeoJSON spec (opposite of how lat/lng is usually said aloud).
    location: {
      type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
      },
      coordinates: {
        type: [Number],
        default: [72.8777, 19.0760],
      },
    },
    isApproved: {
      type: Boolean,
      default: false,
    },
    // True for hospitals auto-created by the nearby-facility provisioner
    // (see backend/utils/autoProvision.js) so a search from any location
    // always has realistic nearby results, not just around the seed data.
    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

hospitalSchema.index({ location: '2dsphere' });

// Keeps the GeoJSON `location` field in sync whenever latitude/longitude
// change, so every existing controller that reads/writes .latitude/.longitude
// keeps working unmodified, while $near geospatial queries also work.
hospitalSchema.pre('save', function syncLocation(next) {
  if (this.isModified('latitude') || this.isModified('longitude') || this.isNew) {
    this.location = { type: 'Point', coordinates: [this.longitude, this.latitude] };
  }
  next();
});

const Hospital = mongoose.model('Hospital', hospitalSchema);
export default Hospital;
